[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pymailfeedback"
version = "0.1.0"
description = "Email yourself automatically when a long-running Python script succeeds or fails — with traceback, attachments, and more"
readme = "README.md"
requires-python = ">=3.7"
authors = [
    { name="Daniele Mascali", email="danielemascali@gmail.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = []
[project.scripts]
pymailfeedback-init = "pymailfeedback.core:_interactive_setup"

[project.urls]
Homepage = "https://github.com/dmascali/pymailfeedback"
Repository = "https://github.com/dmascali/pymailfeedback"
Issues = "https://github.com/dmascali/pymailfeedback/issues"